#ifndef RPG_CHARACTER_REQUEST_TYPE_H_
#define RPG_CHARACTER_REQUEST_TYPE_H_


enum class CharacterRequestType
{
	BASIC_CHARACTER_REQUEST_FOR_FIGHT,
	BASIC_FIGHT_REQUEST,
	BASIC_DESCREAT_2DMAP_REQUEST
};


#endif // !RPG_CHARACTER_REQUEST_TYPE_H_
