#ifndef RPG_CHARACTER_MANAGER_NAME_H_
#define RPG_CHARACTER_MANAGER_NAME_H_


enum class CharacterManagerName
{
	LIFE_MANAGEMENT_SYSTEM,
	TOOL_MANAGEMENT_SYSTEM,
	UNNESSESORY_STUFF_MANAGEMENT_SYSTEM,
	LEVEL_MANAGEMENT_SYSTEM,
	INVENTORY_MANAGEMENT_SYSTEM
};


#endif // !RPG_CHARACTER_MANAGER_NAME_H_

